/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MysteriesRouteImport } from './routes/mysteries'
import { Route as LegendsRouteImport } from './routes/legends'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplesIndexRouteImport } from './routes/temples.index'
import { Route as TemplesSlugRouteImport } from './routes/temples.$slug'

const MysteriesRoute = MysteriesRouteImport.update({
  id: '/mysteries',
  path: '/mysteries',
  getParentRoute: () => rootRouteImport,
} as any)
const LegendsRoute = LegendsRouteImport.update({
  id: '/legends',
  path: '/legends',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesIndexRoute = TemplesIndexRouteImport.update({
  id: '/temples/',
  path: '/temples/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplesSlugRoute = TemplesSlugRouteImport.update({
  id: '/temples/$slug',
  path: '/temples/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/gallery': typeof GalleryRoute
  '/legends': typeof LegendsRoute
  '/mysteries': typeof MysteriesRoute
  '/temples/$slug': typeof TemplesSlugRoute
  '/temples/': typeof TemplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/gallery': typeof GalleryRoute
  '/legends': typeof LegendsRoute
  '/mysteries': typeof MysteriesRoute
  '/temples/$slug': typeof TemplesSlugRoute
  '/temples': typeof TemplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/gallery': typeof GalleryRoute
  '/legends': typeof LegendsRoute
  '/mysteries': typeof MysteriesRoute
  '/temples/$slug': typeof TemplesSlugRoute
  '/temples/': typeof TemplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/gallery'
    | '/legends'
    | '/mysteries'
    | '/temples/$slug'
    | '/temples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/architecture'
    | '/gallery'
    | '/legends'
    | '/mysteries'
    | '/temples/$slug'
    | '/temples'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architecture'
    | '/gallery'
    | '/legends'
    | '/mysteries'
    | '/temples/$slug'
    | '/temples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRoute
  GalleryRoute: typeof GalleryRoute
  LegendsRoute: typeof LegendsRoute
  MysteriesRoute: typeof MysteriesRoute
  TemplesSlugRoute: typeof TemplesSlugRoute
  TemplesIndexRoute: typeof TemplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mysteries': {
      id: '/mysteries'
      path: '/mysteries'
      fullPath: '/mysteries'
      preLoaderRoute: typeof MysteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legends': {
      id: '/legends'
      path: '/legends'
      fullPath: '/legends'
      preLoaderRoute: typeof LegendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/': {
      id: '/temples/'
      path: '/temples'
      fullPath: '/temples/'
      preLoaderRoute: typeof TemplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temples/$slug': {
      id: '/temples/$slug'
      path: '/temples/$slug'
      fullPath: '/temples/$slug'
      preLoaderRoute: typeof TemplesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRoute,
  GalleryRoute: GalleryRoute,
  LegendsRoute: LegendsRoute,
  MysteriesRoute: MysteriesRoute,
  TemplesSlugRoute: TemplesSlugRoute,
  TemplesIndexRoute: TemplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
